#!/bin/bash

echo AWS_USER_POOL_ID=$AWS_USER_POOL_ID >> .env
echo AWS_CLIENT_ID=$AWS_CLIENT_ID >> .env
echo APPLE_ID=$APPLE_ID >> .env
echo APPLE_ID_PASS=$APPLE_ID_PASS >> .env
echo CSC_LINK=$CSC_LINK >> .env
echo CSC_KEY_PASSWORD=$CSC_KEY_PASSWORD >> .env
echo WIN_CSC_LINK=$WIN_CSC_LINK >> .env
echo WIN_CSC_KEY_PASSWORD=$WIN_CSC_KEY_PASSWORD >> .env
